name = "agsm-dashboard"
compatibility_date = "2026-06-25"
pages_build_output_dir = "web"

[[d1_databases]]
binding = "DB"
database_name = "kailas-ogsm-db"
database_id = "4369d638-b623-4737-970c-93529c0c7ff6"
